### ISSUE TITLE
Document early contributing guidelines

### ISSUE THREAD

**Issue by parfei** [Mafia-Hands/Mafia#101]
**Describe the requirement**
Document how we used to contribute to the repo, before we discussed contributing guidelines.
These include:
- [ ] we did not squash early commits and committed straight to master

**Target audience**
Who would benefit from the documentation? 
 - Developers (including future OSS contributers)

**Ideas for the documentation**
Will be updated somewhere in the Wiki. Perhaps a page that is under `Contributing Guidelines.`

### Issue Approval:
- [ ]  Issue approved by:

**Comment by tguernier** [comment]
Done -modified [wiki page](https://github.com/Mafia-Hands/Mafia/wiki/Contributing-Guidelines).
