### ISSUE TITLE
Testing Procedure Documentation

### ISSUE THREAD

**Issue by parfei** [Mafia-Hands/Mafia#102]
**Describe the requirement**
Document how we might write Jest tests, for both the frontend and the backend.

**Target audience**
Who would benefit from the documentation? 
 - Developers

**Ideas for the documentation**
E.g. using AAA or other testing frameworks.

### Issue Approval:
- [x]  Issue approved by: @tguernier

**Comment by seif-y** [comment]
[All done :)](https://github.com/Mafia-Hands/Mafia/wiki/Backend-Testing-Infrastructure)
