### ISSUE TITLE
Document potential features for future work

### ISSUE THREAD

**Issue by parfei** [Mafia-Hands/Mafia#103]
**Describe the requirement**
Document how one might contribute to the project in the future.

**Target audience**
Who would benefit from the documentation? 
 - Developers

**Ideas for the documentation**
This would include things from here: https://docs.google.com/document/d/1IWL0vqVs-JMbHS3oKSCYrkXt_wxb9H6pJySJ5ubHxyE/edit. Other potential issues to look into for future OSS contributers are issues labeled with `future work`.

### Issue Approval:
- [x]  Issue approved by: @tguernier

**Comment by tguernier** [comment]
New future work doc: https://docs.google.com/document/d/1dH0DC6vFdd7Bd5G33ojq-QGigf6E7dmaWJZFLbU9i_s/edit

**Comment by SreenikethRaghavan** [comment]
All the future work issues have been added
