### ISSUE TITLE
Implement Bottom Bar

### ISSUE THREAD

**Issue by reeved** [Mafia-Hands/Mafia#113]
**What are the tasks that need to be done?**
- [x] Add chat box to bottom bar
- [x] Add Day/Night cycle tracker to bottom bar

### In-Depth Feature Description
The BottomBar component is currently empty and should contain some elements as per mockups. 

### Images for Reference:
![image](https://user-images.githubusercontent.com/7234148/111066648-ec9d9800-8524-11eb-8c44-db1c07574b5f.png)

### Feature Approval:
- [x]  Feature approved by: @ateagit (Alan Thomas)

**Comment by skyn310198** [comment]
Agree with the whole team that the chatbox will not be implemented at this stage of the project
