### ISSUE TITLE
Enforce Usage of Material UI as well as custom Components

### ISSUE THREAD

**Issue by reeved** [Mafia-Hands/Mafia#118]
**Describe the requirement**
Make sure developers know to use Material UI library as well as re-using core Components like TopBarGame etc.

**Target audience**
Who would benefit from the documentation? 
 - Developers?

**Ideas for the documentation**
Add it in Contributing Guidelines maybe? 

### Issue Approval:
- [x]  Issue approved by: @tguernier

**Comment by SreenikethRaghavan** [comment]
Developers have been informed about the use of Material UI and re-using components. This has been mentioned in the wiki
