### ISSUE TITLE
Proper Game Over screen implementation

### ISSUE THREAD

**Issue by reeved** [Mafia-Hands/Mafia#122]
**What are the tasks that need to be done?**
- [x] Add Players 
- [x] Use StatusBar component instead of custom header 
- [ ] Implement logic to style text to green/red if the player has won/lost

### In-Depth Feature Description
Current Game Over screen is empty and uses placeholders. Needs to be fully featured for MVP

### Images for Reference:
See mockups and #27 for images

### Feature Approval:
- [x]  Feature approved by: @ateagit (Alan Thomas)

**Comment by tguernier** [comment]
PR closed without merge
