### ISSUE TITLE
Global ESlint Config File / Refactor

### ISSUE THREAD

**Issue by MKTPR** [Mafia-Hands/Mafia#125]
**Is your feature request related to a problem? Please describe.**
Currently, the ESLint config files are stored separately for backend and frontend. This prevents the pre-commit hook from running both the lint tests and instead, only runs one. Also, to enforce consistency in the entire project, it would be better to have one global config file. 

**Describe the solution you'd like**
Global config file in the root directory which stores the rules for both frontend and backend. 

**Describe alternatives you've considered**
Separate config files for frontend and backend (current structure)

**Additional context**

### Checklist:
- [ ] Frontend
- [ ] Backend

### Feature Approval:
- [x]  Feature approved by: @parfei

**Comment by reeved** [comment]
We will continue with this issue once the Backend-Frontend integration is complete and the final feature-freeze is in place :)
