### ISSUE TITLE
Prevent dead players from voting

### ISSUE THREAD

**Issue by ateagit** [Mafia-Hands/Mafia#165]
**Describe the bug**
Dead players are still allowed to vote in voting events e.g. mafia-vote, trial-vote, day-vote

**To Reproduce**
1. Go to Game and die in the game 
2. Observe that players are still hoverable and clickable in game

**Expected behavior**
Dead Players shouldnt be able to vote: that is, other players shouldnt be hoverable or clickable

### Issue Approval:
- [x]  Issue approved by: MKTPR

**Comment by parfei** [comment]
Duplicate issue with https://github.com/Mafia-Hands/Mafia/issues/161

**Comment by SiyuQian** [comment]
Confirmed this is a duplicate issue with #161 so I am going to close this one.
