### ISSUE TITLE
Settings button on the right corner not working

### ISSUE THREAD

**Issue by SiyuQian** [Mafia-Hands/Mafia#172]
## Description
After the role assigned, in the game screen the settings button is not working

**To Reproduce**
1. Start the game
2. Click on 'settings'

**Expected behavior**
Once the user click on the settings button, the setting dialog/panel should popup

**Screenshots**
<img width="1038" alt="Screen Shot 2021-03-18 at 4 03 42 PM" src="https://user-images.githubusercontent.com/24470452/111567317-9f127b00-8803-11eb-8212-a1ea2893d330.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.2
 - Browser: Google Chrome
 - Version: 89.0.4389.90

### Issue Approval:
- [x]  Issue approved by: @reeved

**Comment by reeved** [comment]
This has been fixed in #160. However I would like to explore a neater solution because my solution used a lot of repeated code!

**Comment by SiyuQian** [comment]
@reeved Ok.. So I guess I should close the ticket and you might create another about the enhancement part.
