### ISSUE TITLE
Installation instructions in README are incomplete

### ISSUE THREAD

**Issue by DarkMatterMatt** [Mafia-Hands/Mafia#173]
**Describe the requirement**
README should contain sufficient instructions to be able to install dependencies & build the project.

**Target audience**
Who would benefit from the documentation? 
- Contributors
- Self-hosting users

**Ideas for the documentation**
Have basic instructions for installing and running the project. Have link to wiki if more information is required.

### Issue Approval:
- [x]  Issue approved by: @reeved

**Comment by parfei** [comment]
As mentioned in https://github.com/Mafia-Hands/Mafia/pull/174, it would be nice to include test commands as well.
