### ISSUE TITLE
Frontend comprehensive styling

### ISSUE THREAD

**Issue by Jmcl168** [Mafia-Hands/Mafia#193]
**What are the tasks that need to be done?**
- [x] Home page
- [x] Lobby
- [x] Entry screen
- [x] Settings
- [x] Game Environment
- [x] Game over screen

### In-Depth Feature Description
Make styling for all screens and components the same for a more comprehensive game design.
Using Helvetica font and this colour palette:
![161300372_262167702038549_5597630572452014120_n](https://user-images.githubusercontent.com/61758619/111722831-7c499a80-88c7-11eb-8346-c7995f6c2e84.png)
#3E5B7F           #98C1D9          #E3F1F1          #293241          #EE6644

### Images for Reference:
<img width="1019" alt="Screen_Shot_2021-03-19_at_3 08 14_PM" src="https://user-images.githubusercontent.com/61758619/111722206-40620580-88c6-11eb-81b0-bed61946fa22.png">
<img width="1016" alt="Screen_Shot_2021-03-19_at_3 08 25_PM" src="https://user-images.githubusercontent.com/61758619/111722205-3fc96f00-88c6-11eb-92a0-7ae3deca472f.png">
<img width="1017" alt="Screen_Shot_2021-03-19_at_3 08 41_PM" src="https://user-images.githubusercontent.com/61758619/111722202-3e984200-88c6-11eb-8375-eb0ba34dd8ec.png">
<img width="1018" alt="Screen_Shot_2021-03-19_at_3 09 05_PM" src="https://user-images.githubusercontent.com/61758619/111722208-40fa9c00-88c6-11eb-95b4-21ce11a3dfa1.png">
<img width="1017" alt="Screen_Shot_2021-03-19_at_3 08 54_PM" src="https://user-images.githubusercontent.com/61758619/111722209-41933280-88c6-11eb-9771-11a364c38118.png">

### Feature Approval:
- [x]  Feature approved by: @SiyuQian

**Comment by reeved** [comment]
Mocks look great!
