### ISSUE TITLE
amIDead and isDead confusing variable

### ISSUE THREAD

**Issue by parfei** [Mafia-Hands/Mafia#229]
**Is your feature request related to a problem? Please describe.**
In `Player.jsx`, in order to determine whether a player circle is hoverable or not, we check whether the current player is dead (because you won't be able to hover over _any_ circles) and whether the circle that is currently being hovered over is dead or not.

The variable names `amIDead` or `isDead` represent this and are a bit confusing.

**Describe the solution you'd like**
Rename the respective variables to something that is more descriptive. For instance, `isDead` and `currentHoveredPlayerIsDead`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### Feature Approval:
- [x]  Feature approved by: @MKTPR

**Comment by Rishabhraghwendra18** [comment]
Hi @parfei 😃 , I am currently learning to write Clean Code . I think I can help you in this .
