### ISSUE TITLE
Jester revealed as mafia for the detective

### ISSUE THREAD

**Issue by SreenikethRaghavan** [Mafia-Hands/Mafia#267]
**Describe the bug**
Currently, if the detective queries the jester, it reveals them as mafia. This was initially done as an intentional implementation to ensure that the jester is not revealed as a member of the town. 

However, this can be misleading for the detective as they might think the jester is the mafia. 

**To Reproduce**
1. Start the game with 6 instances of the app
2. Go to the tab with the detective role
3. Query the player with the jester role

**Expected behavior**
The jester should either be revealed as not-mafia or not part of the town

**Additional context**
This was initially done as an intentional implementation to ensure that the jester is not revealed as a member of the town.

**Desktop (please complete the following information):**
 - OS: Windows + Mac
 - Browser: Chrome

### Issue Approval:
- [x]  Issue approved by: JChamberlain28

**Comment by reeved** [comment]
This is intentional? We want to make it difficult for the Detective otherwise their power is OP.

I do agree that the wording could be changed from "MAFIA" and "NOT MAFIA" to "BAD" and "GOOD".

**Comment by JChamberlain28** [comment]
The change that will be implemented will be to change to 'not mafia' as it should be hard for the detective (shouldn't be able to detect the jester). This avoids revealing them as mafia and makes them indistinguishable from civilians as the detective only knows if someone is mafia or not.
