### ISSUE TITLE
Addition of background music to the game

### ISSUE THREAD

**Issue by SreenikethRaghavan** [Mafia-Hands/Mafia#270]
**Is your feature request related to a problem? Please describe.**
It is not as engaging to not having some background music playing in the game

**Describe the solution you'd like**
The addition of background music in the game

**Describe alternatives you've considered**
Having some random beats playing 

**Additional context**
This issue is linked to #265 

### Feature Approval:
- [ ]  Feature approved by:

**Comment by milkyway404** [comment]
Recording in #325
