### ISSUE TITLE
Addition of player avatars and animations

### ISSUE THREAD

**Issue by SreenikethRaghavan** [Mafia-Hands/Mafia#272]
**Is your feature request related to a problem? Please describe.**
I cannot distinguish between players apart from their names. Also, there is no animation when someone is killed/saved. 

**Describe the solution you'd like**
- The ability for players to choose avatars/icons. 
- Also the addition of animations when a player is killed or during other significant events. 

### Feature Approval:
- [ ]  Feature approved by:

**Comment by Benjamin-Piper** [comment]
As this issue is too broad, we've decided to close this issue and open more specific design issues:

- #304
- #305
- #306
- #307
- #308
- #309
- #310
- #311
- #312
- #313
- #314
- #315
- #316
- #317
