### ISSUE TITLE
Redesign of user avatars

### ISSUE THREAD

**Issue by lhuijser** [Mafia-Hands/Mafia#305]
### What are you proposing?

- Replace circles representing players with new avatar icons
- Add faces to the avatars depending on if they are alive or dead
- Move the nickname of the player to the bottom of the avatar (note if the positioning shown in the hi-fi design does not work, putting the name below the avatar is fine)

### Is this ready to implement?

Yes.

Hi-fi prototype: https://www.figma.com/file/zoB3yUb1s6WonkGmRZcRYR/MAFIA-Assignment-2?node-id=327%3A250

Screenshots of new design:
<img width="307" alt="Screen Shot 2021-04-08 at 7 11 28 PM" src="https://user-images.githubusercontent.com/54383847/113983624-3a948a00-989e-11eb-8fa3-acfbb7e0b906.png">
<img width="537" alt="Screen Shot 2021-04-08 at 7 12 04 PM" src="https://user-images.githubusercontent.com/54383847/113983678-4f711d80-989e-11eb-9d4d-798341198c62.png">

Assets that can be used for this:

![alive](https://user-images.githubusercontent.com/54383847/113983488-120c9000-989e-11eb-99eb-323ba3c1425c.png)
![dead](https://user-images.githubusercontent.com/54383847/113983493-12a52680-989e-11eb-8850-888b433d3699.png)
![685-6851196_person-icon-grey-hd-png-download](https://user-images.githubusercontent.com/54383847/113983717-5d26a300-989e-11eb-89d9-7423ca75dac5.png)

### Redesign approval:

- [X] Redesign approved by: @Benjamin-Piper

**Comment by Benjamin-Piper** [comment]
I approve! I love how the avatars have expressions now!
