### ISSUE TITLE
Redesign of 'voted' symbol indicating a user has voted on something

### ISSUE THREAD

**Issue by lhuijser** [Mafia-Hands/Mafia#306]
### What are you proposing?

- Replace the red dot that currently appears on each user when they vote on something with a 'voted!' symbol above the avatar.

### Is this ready to implement?

Yes.

Hi-fi prototype: https://www.figma.com/file/zoB3yUb1s6WonkGmRZcRYR/MAFIA-Assignment-2?node-id=327%3A250

Screenshots of new design:
<img width="278" alt="Screen Shot 2021-04-08 at 7 21 25 PM" src="https://user-images.githubusercontent.com/54383847/113984828-9f9caf80-989f-11eb-952c-ce37e8e6d7c5.png">

No extra assets to add.

### Redesign approval:

- [X] Redesign approved by: @Benjamin-Piper

**Comment by Benjamin-Piper** [comment]
Nice! I approve!
