### ISSUE TITLE
Redesign of voting to kill or abstain system

### ISSUE THREAD

**Issue by lhuijser** [Mafia-Hands/Mafia#307]
### What are you proposing?

- Replace the 'click on the user to vote to kill them, or click abstain' system with a thumbs up (kill) or thumbs down (no confidence) two-button system below the newly created platform in the middle of the screen. 
- After timer runs out/everyone has voted, people's votes are now revealed by showing a thumbs up or thumbs down icon below each player. 
- The system to be replaced can be seen here:
<img width="180" alt="Screen Shot 2021-04-06 at 12 11 39 PM" src="https://user-images.githubusercontent.com/54383847/113987129-25215f00-98a2-11eb-9e52-5075909e412c.png">

### Is this ready to implement?

Yes.

Hi-fi prototype: https://www.figma.com/file/zoB3yUb1s6WonkGmRZcRYR/MAFIA-Assignment-2?node-id=309%3A259

Screenshots of new design:
<img width="562" alt="Screen Shot 2021-04-08 at 8 56 21 PM" src="https://user-images.githubusercontent.com/54383847/113998148-e47b1300-98ac-11eb-9873-5ab1cfbcd6d4.png">
<img width="289" alt="Screen Shot 2021-04-08 at 7 40 56 PM" src="https://user-images.githubusercontent.com/54383847/113987289-59951b00-98a2-11eb-9c35-b8ce94776417.png">

Assets:
Material UI thumbs up and down icons can be used

### Redesign approval:

- [X] Redesign approved by: @Benjamin-Piper

**Comment by Benjamin-Piper** [comment]
Quick question: should we change abstain to No confidence? Because in the backend there's been a variable change, see this closed issue #163

**Comment by lhuijser** [comment]
> Quick question: should we change abstain to No confidence? Because in the backend there's been a variable change, see this closed issue #163

Good point, I agree with the change to no confidence to make it more consistent :) Just updated! Thanks for pointing this out

**Comment by Benjamin-Piper** [comment]
Great, I approve then!
