### ISSUE TITLE
Create Routed Pages

### ISSUE THREAD

**Issue by reeved** [Mafia-Hands/Mafia#31]
**What are the tasks that need to be done?**
- [x] Created `/` - Homescreen
- [x] Created `/play` - Game Screen

### In-Depth Feature Description
Could have `/play/{:id}` to allow people to join the game quickly by going to that link?

**Comment by SiyuQian** [comment]
I could do the routing with URL parameters when the application got more completed or the design is fixed a bit. Since the application is still in a very early stage so it's no point to get this feature done.

**Comment by reeved** [comment]
> I could do the routing with URL parameters when the application got more completed or the design is fixed a bit. Since the application is still in a very early stage so it's no point to get this feature done.

agreed :)
