### ISSUE TITLE
Update screen diagrams in the wiki

### ISSUE THREAD

**Issue by Benjamin-Piper** [Mafia-Hands/Mafia#311]
**Describe the requirement**

To replace the link that the sidebar bullet `Screen Diagams/Wireframes` points to with a new page full of the new redesigned screen diagrams.

This way we keep the old screen diagrams and we have it point to a new page with our new screen diagrams.

**Target audience**
Who would benefit from the documentation? 
- Developers
- Designers

**Ideas for the documentation**

- Provide a link to the old screen diagrams page
- Provide a link to all Figma's used for the new screen diagrams
- Provide screenshots for each new screen diagram
  - They should be organised in a similar order to the old screen diagrams page

### Issue Approval:
- [x] Issue approved by: @AngelaLH

**Comment by AngelaLH** [comment]
Screen diagrams updated in the wiki + old screen diagrams archived 
View here: 
https://github.com/Mafia-Hands/Mafia/wiki/Screen-Diagrams--Wireframes
