### ISSUE TITLE
Redesign of the Role Reveal screen

### ISSUE THREAD

**Issue by AngelaLH** [Mafia-Hands/Mafia#315]
### What are you proposing?

- Redesign of the Role Reveal screen

### Is this ready to implement?
Yes:
#### Screenshots
![Game Screen (Just entered)](https://user-images.githubusercontent.com/41172492/114253651-17352080-99ff-11eb-822b-434a7d7c5c48.png)
Figma: https://www.figma.com/file/zoB3yUb1s6WonkGmRZcRYR/MAFIA-Assignment-2?node-id=309%3A259 Under Game Screen (just entered)
Card heading font: Audiowide
Other Font: Roboto
Colours:
In ./Styles/colourScheme.css
Green - #9EFF8E
Red - #F76C6C
Yellow - #E9E843
Background - #A4B8C4
Day Card Background - #C8D3D5
Night Card Background - #293241
Black text - #2B282A
White Text - #FFFFFF

#### Assets
[MAFIA Assignment 2 (1).zip](https://github.com/Mafia-Hands/Mafia/files/6289053/MAFIA.Assignment.2.1.zip)
Also:
[Avatars without face.zip](https://github.com/Mafia-Hands/Mafia/files/6289108/Avatars.without.face.zip)
Smiley face can be found in #305 

Note: this can be done in conjunction with #313 Redesign of help screen as the reveal cards are identical

The timer, Name and settings part will be implemented in #314 

### Redesign approval:

- [ ] Redesign approved by:

**Comment by JChamberlain28** [comment]
Unassigned due to issue blocking. Currently assigned to the contributor working on the issue blocking this. This issue is a small and natural progression from that one so it makes sense to assign in this way.

**Comment by yzho976** [comment]
If Jack got a clue about preventing code repetition, it would be better to unassign me.

**Comment by JChamberlain28** [comment]
Please read my communication on other channels with you. I assessed that the code repetition and the way cards are currently implemented meant this issue cannot be completed in a suitable time frame. I am unassigning all from the issue now.
