### ISSUE TITLE
Fix frontend roles and rules looking squished

### ISSUE THREAD

**Issue by milkyway404** [Mafia-Hands/Mafia#341]
**Describe the bug**
See screenshot.

**To Reproduce**
1. Create a new game.
2. Look up rules.

**Expected behavior**
All the cards should be separated out as designed in the wiki.

**Screenshots**
![image](https://user-images.githubusercontent.com/50122790/114960084-7214bf00-9eba-11eb-96f2-1cf8e37156d5.png)

### Issue Approval:
- [x]  Issue approved by: @khal745

**Comment by milkyway404** [comment]
Note that I will work on this issue since it seems to be my resolution that does it.

**Comment by khal745** [comment]
Have a similar issue on my resolution, so can verify that this issue exists for my resolution as well
![bitSmushed](https://user-images.githubusercontent.com/49116468/114960204-abe5c580-9eba-11eb-9445-acc0e839cb7e.png)

**Comment by ysway** [comment]
I guess

https://github.com/Mafia-Hands/Mafia/blob/04869585793f00d4bf4c3edb54b70cf491ac8456/frontend/src/Styles/NewGameScreen.module.css#L6
