### ISSUE TITLE
Socket.io Event Handeling

### ISSUE THREAD

**Issue by absternator** [Mafia-Hands/Mafia#48]
#### Description
This is the setup of socket.io event handling for the different states of the game. It shall interact with the Client to pass information back and forth and update the client in real-time. 

Tasks:
 - [ ] Create skeleton event handlers for all game states
 - [ ]  Fill in event handlers with relevant logic - requires #45 
 - [ ]  Create tests and test the feature works as inteded
 

- [ ]  This issue is approved by 1 or more other members of the team. Approvers: ___

**Comment by seif-y** [comment]
We are getting rid of this issue, and creating smaller issues to handle each specific event handling cases
