### ISSUE TITLE
Add game design documents to wiki

### ISSUE THREAD

**Issue by parfei** [Mafia-Hands/Mafia#54]
**Describe the requirement**
Document game design documents into the wiki. Helps new OSS contributors to our project.

**Target audience**

Developers
End users
Designers
Testers
& all that want to learn how the game flows + looks like.

**Ideas for the documentation**
- [x] User flow diagram
- [x] Mock wireframes
- [x] Game rules

Issue Approval:
- [ ] Issue approved by:

**Comment by tguernier** [comment]
Done

User flow diagram/ wireframes: https://github.com/Mafia-Hands/Mafia/wiki/Game-Structure-Design
Game rules: https://github.com/Mafia-Hands/Mafia/wiki/Game-Rules
