### ISSUE TITLE
Creating Socket class in frontend to communicate with backend

### ISSUE THREAD

**Issue by ateagit** [Mafia-Hands/Mafia#74]
There needs to be a way for the frontend to communicate with the backend. This will be done using a class that encapsulates the socket io logic in one place.

**What are the tasks that need to be done?**
- [ ] Set up client socket io.
- [ ] Create methods used by the GameState class to notify the server.
- [ ] Create methods to be provided by GameState (create empty methods as it doesn't exist) to change the game state. 
- [ ] Satisfy all the events listed out in the following doc https://docs.google.com/document/d/1_Pz4MDuEugBjkOiRBAQwPHmd0UnqeSaetcr3SKP10Fc/edit

### In-Depth Feature Description
**Describe alternatives you've considered**
- Allowing the socket to be accessed by any component. This will mean that components are responsible for updating the game state and I think one global state is better. 
- Putting game state logic and sockets together. This would probably result in large methods and is not reliable as the server api may change in the future. 

**Additional context**
Because the GameState class hasn't been made yet, this task will involve creating an empty GameState class file filled with empty methods that Socket will rely on. 

Because the server hasn't been set up yet, this functionality will be hard to test. Rather than correctness, focus on getting the class methods completed so other tasks aren't blocked.

### Images for Reference:
Read more here: https://drive.google.com/file/d/1SIIzjz2DufRALeQevyrHJXH25iHO0NsP/view?usp=sharing

### Feature Approval:
- [x]  Feature approved by: Reeve

**Comment by reeved** [comment]
Looks good.
