### ISSUE TITLE
Creating GameState class for frontend

### ISSUE THREAD

**Issue by ateagit** [Mafia-Hands/Mafia#75]
There needs to be a class that manages the game state. 

**What are the tasks that need to be done?**
- [ ] Create fields that will be used to hold game state. 
- [ ] Create methods that will be used to modify game state. 
- [ ] Complete methods provided by #74 

### In-Depth Feature Description
Some methods will be already created by the Socket class as a way to mutate state from events from server.
React Components will be calling these methods from arising game events e.g. voted for player X by pressing a player. Name methods correspondingly. 
More details will be provided on the completion of #74 

Blocked by #74 
### Images for Reference:
Read more here: https://drive.google.com/file/d/1SIIzjz2DufRALeQevyrHJXH25iHO0NsP/view?usp=sharing

### Feature Approval:
- [x]  Feature approved by: Reeve

**Comment by reeved** [comment]
@ateagit Do we need this issue open anymore?

**Comment by reeved** [comment]
Closing since this has now been implemented.
