### ISSUE TITLE
Create Socket.IO API Documentation

### ISSUE THREAD

**Issue by parfei** [Mafia-Hands/Mafia#76]
**Describe the requirement**
The backend team has finished rough planning of a backend architecture #34. We've decided that it would be best to create documentation for the frontend team on how we've decided to send/receive Socket.IO events.

This API documentation will describe how the server and the client communicates via specified events. These are essentially Socket.io "endpoints". This is very important for development as it will strictly define an interface that the frontend and the backend will use as communication; the documentation ensures consistency, and will be updated throughout the lifetime of the project.

- [x] First draft of the API
- [x] Sync with the frontend team and make appropriate adjustments
- [ ] All final adjustments made

**Target audience**
Who would benefit from the documentation? 
 - Developers

**Ideas for the documentation**
It should contain all events that will be passed between the client and the server. In the API documentation, include a description of each event, include the request body format and the response behaviour that will occur.

### Issue Approval:
- [x]  Issue approved by: Seif

**Comment by parfei** [comment]
API documentation created: https://docs.google.com/document/d/1_Pz4MDuEugBjkOiRBAQwPHmd0UnqeSaetcr3SKP10Fc/edit

**Comment by parfei** [comment]
Meeting sync'd with frontend team, Friday 4pm NZDT.
- enforce on server that each player has an unique nickname
- need negative handling cases -- we can ignore for the MVP for now + the disconnection during game
- no changing of votes for mafia, detective, medic, day, trial
- socket endpoints up by Saturday (but event handlers will have dummy implementation)
- we will be updating this [google doc always](https://docs.google.com/document/d/1_Pz4MDuEugBjkOiRBAQwPHmd0UnqeSaetcr3SKP10Fc/edit) 

- resources on socket.io for fronted: passed in the frontend chnl + notes-resources

- timer & game state stored in backend

**Comment by tguernier** [comment]
Done
