### ISSUE TITLE
Add Timer to TopBarGame

### ISSUE THREAD

**Issue by reeved** [Mafia-Hands/Mafia#86]
**What are the tasks that need to be done?**
- [x] Add Timer to TopBarGame
- [x] Make sure it blends in well aesthetically

### In-Depth Feature Description
We now need to add the Timer component to the TopBarGame component. Initial version will still have a button to fire off the timer but a final implementation will require communication with the server for this functionality.

### Feature Approval:
- [x]  Feature approved by: @ateagit (Alan Thomas)

**Comment by ateagit** [comment]
> **What are the tasks that need to be done?**
> 
> * [ ]  Add Timer to TopBarGame
> * [ ]  Make sure it blends in well aesthetically
> 
> ### In-Depth Feature Description
> We now need to add the Timer component to the TopBarGame component. Initial version will still have a button to fire off the timer but a final implementation will require communication with the server for this functionality.
> 
> ### Images for Reference:
> ### Feature Approval:
> * [ ]   Feature approved by: @ateagit  (Alan Thomas)
