### ISSUE TITLE
Reposition Dialog components

### ISSUE THREAD

**Issue by SiyuQian** [Mafia-Hands/Mafia#93]
## Current
The Dialog files are positioning in the Pages folder which is not correct. They should be placed in the components folder. 
Also, The Dialog should be a single component instead of having two: RoleAndRuleDialog.js and SettingDialog.js.

## Suggest
We could have only one component called Dialog and the file should be positioned in the 'Components' folder.

Please have a look at this and share what you think. @jge385 and @reeved

**Comment by atha670** [comment]
Both these dialogues have different functionalities so I think they should be kept separate but I have moved them to components. Might be better I just rename the files.

**Comment by reeved** [comment]
Closing so that we can create a new "Code Refactor/Cleanup" issue in the future.
